### ISSUE TITLE
Loads model from file path in Android fail

### ISSUE THREAD

**Issue by WizardHsuWeiChe** [Macoron/whisper.unity#67]
I built the apk and ran it on the Quest2, there is an error for not finding the model. The model is under the StreamingAssets and the "Is Model Path In Streaming Assets" is enabled. After doing the investigation, it seems we should use UnityWebRequest to access StreamingAssest on Android and WebGL platforms. So after the adjustment in WhisperWrapper.cs the issue is fixed:
 ```
      public static WhisperWrapper InitFromFile(string modelPath, WhisperContextParams contextParams)
        {
#if UNITY_ANDROID && !UNITY_EDITOR
            var buffer = FileUtils.ReadFileWebRequest(modelPath); // this line is modified
            var res = InitFromBuffer(buffer, contextParams);
            return res;
#else
```
I hope my fix makes sense or maybe there are some settings I am missing in my project. Thank you

**Comment by Macoron** [comment]
I unable to replicate this locally on my Google Pixel 4. Original code looks like this:
https://github.com/Macoron/whisper.unity/blob/25c8d267cf219f6a6728c6b35d6566c4a4d1aefd/Packages/com.whisper.unity/Runtime/WhisperWrapper.cs#L272-L278

Where `FileUtils.ReadFile` is:
https://github.com/Macoron/whisper.unity/blob/25c8d267cf219f6a6728c6b35d6566c4a4d1aefd/Packages/com.whisper.unity/Runtime/Utils/FileUtils.cs#L13-L19

It should work same, because `FileUtils.ReadFile` will call `FileUtils.ReadFileWebRequest` on Android.

**Comment by Macoron** [comment]
Reopen issue, if you have more info
